/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shoe.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shoe.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Shoe.geometry} material={materials.phong1SG} position={[0.002, 0.076, 0.005]} scale={0.149} />
    </group>
  )
}

useGLTF.preload('/shoe.glb')
